language: python

python:
- '3.6'

install:
- pip install -U pip setuptools mypy flake8
- pip install -r requirements.txt

script:
# First run the type checker and the tests to make sure everything is fine
- flake8
- mypy trust_stores_observatory main.py
- python run_tests.py
# Then fetch the new stores
- python main.py --refresh
- source ./should_travis_deploy
# Export the trust stores as PEM to ./export
- python main.py --export
# Export the trust stores as YAML to ./export
- cp ./trust_stores/* ./export

before_deploy:
# Setup SSH key to be used for commiting the updated trust stores
- openssl aes-256-cbc -K $encrypted_b04627534382_key -iv $encrypted_b04627534382_iv
  -in .travis/travis.key.enc -out .travis/travis.key -d
- eval "$(ssh-agent -s)"
- chmod 600 .travis/travis.key
- ssh-add .travis/travis.key

deploy:
  provider: script
  skip_cleanup: true
  on:
    condition: $SHOULD_TRAVIS_DEPLOY = 1
  script: .travis/push_changes_to_git.sh
