language: python

python:
- '3.6'

install:
- pip install -U pip setuptools
- pip install -r requirements.txt

script:
- python refresh_trust_stores.py
- source ./should_travis_deploy
# Export the trust stores as PEM to ./export
- python export_trust_stores.py
# Export the trust stores as YAML to ./export
- cp ./trust_stores/* ./export

before_deploy:
# Setup SSH key to be used for commiting the updated trust stores
- openssl aes-256-cbc -K $encrypted_b04627534382_key -iv $encrypted_b04627534382_iv
  -in .travis/travis.key.enc -out .travis/travis.key -d
- eval "$(ssh-agent -s)"
- chmod 600 .travis/travis.key
- ssh-add .travis/travis.key

deploy:
  provider: script
  skip_cleanup: true
  on:
    condition: $SHOULD_TRAVIS_DEPLOY = 1
  script: .travis/push_changes_to_git.sh
