language: python

python:
- '3.6'

install:
- pip install -U pip setuptools
- pip install -r requirements.txt

script:
- python refresh_trust_stores.py
- source ./should_travis_deploy

before_deploy:
# Setup SSH key to be used for commiting the updated trust stores
- openssl aes-256-cbc -K $encrypted_b04627534382_key -iv $encrypted_b04627534382_iv
  -in .travis/travis.key.enc -out .travis/travis.key -d
- eval "$(ssh-agent -s)"
- chmod 600 .travis/travis.key
- ssh-add .travis/travis.key

# Export the trust stores as PEM
- python export_trust_stores.py
- cd ./export
- tar -zcf trust_stores_as_pem.tar.gz *
- mv trust_stores_as_pem.tar.gz ../docs
- cd ..

deploy:
  skip_cleanup: true
  on:
    condition: $SHOULD_TRAVIS_DEPLOY = 1

# Switch to SSH Git remote
- git remote set-url origin git@github.com:nabla-c0d3/trust_stores_observatory.git
- git checkout master

# Commit any changes to the trust stores
- git commit -am 'Automated update of the trust stores [ci skip]'
- git push
